name: Smart Zero Downtime Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/todo-app
            git pull origin main
            sudo docker build -t todo-app .

            if grep -q 3001 /etc/nginx/sites-available/default; then
              TARGET=green
              PORT=3002
              OLDPORT=3001
            else
              TARGET=blue
              PORT=3001
              OLDPORT=3002
            fi

            sudo docker stop todo-$TARGET || true
            sudo docker rm todo-$TARGET || true

            sudo docker run -d -p $PORT:3000 --name todo-$TARGET todo-app

            for i in {1..10}; do
            curl -f http://localhost:$PORT && break
            echo "Waiting for app..."
            sleep 5
            done

            sudo sed -i "s/$OLDPORT/$PORT/g" /etc/nginx/sites-available/default
            sudo nginx -t
            sudo systemctl reload nginx